# ---------- STAGE 1: BUILD ----------
FROM node:18 AS builder
WORKDIR /app

# Manifestos (cache)
COPY package*.json ./

RUN npm ci

# Código e build
COPY . .
RUN npm run build

# ---------- STAGE 2: RUNTIME ----------
FROM node:18
WORKDIR /app

# Args -> Envs
ARG PORT
ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASS
ARG JWT_SECRET
ARG JWT_REFRESH_SECRET
ARG JWT_ISS
ARG JWT_AUD
ARG JWT_ALG
ARG ACCESS_TOKEN_TTL
ARG REFRESH_TOKEN_TTL
ARG BCRYPT_SALT_ROUNDS
ARG CORS_ORIGINS
ARG LOG_LEVEL
ARG API_COMUNICACOES_URL

ENV PORT=$PORT
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS
ENV JWT_SECRET=$JWT_SECRET
ENV JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET
ENV JWT_ISS=$JWT_ISS
ENV JWT_AUD=$JWT_AUD
ENV JWT_ALG=$JWT_ALG
ENV ACCESS_TOKEN_TTL=$ACCESS_TOKEN_TTL
ENV REFRESH_TOKEN_TTL=$REFRESH_TOKEN_TTL
ENV BCRYPT_SALT_ROUNDS=$BCRYPT_SALT_ROUNDS
ENV CORS_ORIGINS=$CORS_ORIGINS
ENV LOG_LEVEL=$LOG_LEVEL
ENV API_COMUNICACOES_URL=$API_COMUNICACOES_URL

# Prod deps
COPY package*.json ./
RUN npm ci --omit=dev

# Artefatos de build
COPY --from=builder /app/dist ./dist

EXPOSE 7772
CMD ["npm", "start"]

